# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f13fafbdc95308d329c19b50eeaf18b1303970e962b9efb4abff7509b471151228d5b093940b79b9070c5ec365ea76f119f55463e4263f0c5882b33243d34c88
test:
  secret_key_base: 01185b1d9d160932a12dc38e27d85c5fa9d5bbc2cc16ef5944735e97397220b0e74ea341acee9e5b3c3dd941b88b3fdec11050bc47da58bb1ef633f6ed93b251
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>